name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    tags:
      - "*" # Trigger on all tag pushes

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image tag
        id: docker_tag
        run: |
          if [[ ${{ github.ref_type }} == 'branch' ]]; then
            echo "tag=main" >> $GITHUB_ENV
          elif [[ ${{ github.ref_type }} == 'tag' ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.tag }}
